cp -rfv /usr/local/hadoop/etc/hadoop/slaves /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/masters /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/hdfs-site.xml /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/yarn-site.xml /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/mapred-site.xml /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/core-site.xml /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/hadoop/etc/hadoop/hadoop-env.sh /root/cluster-computing/configs/hadoop/
cp -rfv /usr/local/spark/conf/masters /root/cluster-computing/configs/spark/
cp -rfv /usr/local/spark/conf/slaves /root/cluster-computing/configs/spark/
cp -rfv /usr/local/spark/conf/spark-env.sh /root/cluster-computing/configs/spark/
cp -rfv /usr/local/spark/conf/spark-defaults.conf /root/cluster-computing/configs/spark/
