#!/bin/bash

# Script to setup iptables firewall on ralph.
# Inspired by monofuel.

shopt -o -s errexit nounset

info() {
        echo "[+] $1"
}

# Network interfaces.
# Wide Area Network: WMU
readonly WAN="eth0"
# Local Area Network: cclub office
readonly LAN="eth1"

info 'Flushing all chains'
iptables -F
iptables -t nat -F

info 'Setting default input policy (drop from WAN, accept from LAN)'
# TODO: DROP by default on $WAN, but ACCEPT by default on LAN
#iptables -P INPUT DROP
iptables -P INPUT ACCEPT
iptables -A INPUT -i $LAN -j ACCEPT
iptables -A INPUT -i $WAN -m state --state RELATED,ESTABLISHED -j ACCEPT
info 'Setting default output policy (accept all)'
iptables -P OUTPUT ACCEPT

info 'Enabling ping'
iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

iptables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT

info 'Allowing all traffic on loopback'
iptables -I INPUT -i lo -j ACCEPT
iptables -I OUTPUT -o lo -j ACCEPT

info 'Enabling ssh (tcp port 22)'
iptables -I INPUT -p TCP --dport 22 -i $WAN -j ACCEPT

info 'Enablling dns (tcp/udp port 53)'
iptables -I INPUT -p UDP --dport 53 -j ACCEPT
iptables -I INPUT -p TCP --dport 53 -j ACCEPT
iptables -I OUTPUT -p UDP --dport 53 -j ACCEPT
iptables -I OUTPUT -p TCP --dport 53 -j ACCEPT

info 'Enabling port forwarding'
# The kernel doesn't allow ip forwarding by default. The option is enabled
# through the /proc pseudo-filesystem.
echo 1 > /proc/sys/net/ipv4/ip_forward
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 1 > $f; done

info 'Setting up NAT'
# Enable port masquerading on WAN.
iptables -t nat -A POSTROUTING -o $WAN -j MASQUERADE
# Allow port forwarding to originate from WAN only if it is related or
# established already (from LAN).
iptables -A FORWARD -i $WAN -o $LAN -m state \
        --state RELATED,ESTABLISHED -j ACCEPT
# Allow all port forwarding originating from LAN.
iptables -A FORWARD -i $LAN -o $WAN -j ACCEPT

info 'Forwarding ports'

host_ip=""
for_host() {
        host=$1
        host_ip=$(host $host | awk '{ print $4 }')
        echo -e "\t>> $host ($host_ip)"
}
forward() {
        from=$1
        if [ $# -eq 2 ]; then
                to=$2
        else
                to=$from
        fi
        iptables -t nat -I PREROUTING -p tcp --dport $from -i $WAN -j DNAT \
                --to ${host_ip}:${to}
        echo -e "\t\t$from -> $to"
}

. /etc/opt/forwards

info 'Saving changes to disk'
iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6